<?php
/** @var \Punga\Component\PungaMail\Administrator\View\Topics\HtmlView $this */
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Language\Text; use Joomla\CMS\Layout\LayoutHelper; use Joomla\CMS\Router\Route; use Punga\Component\PungaMail\Administrator\Service\AdministratorRoute;
$order = (string) $this->state->get('list.ordering'); $direction = (string) $this->state->get('list.direction');
?>
<form action="<?php echo Route::_(AdministratorRoute::topics()); ?>" method="post" name="adminForm" id="adminForm">
	<?php echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]); ?>
	<div class="table-responsive"><table class="table itemList"><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGLOBAL_TITLE'), 'a.title', $direction, $order); ?></th><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JFIELD_ALIAS_LABEL'), 'a.alias', $direction, $order); ?></th><th><?php echo Text::_('COM_PUNGAMAIL_SUBSCRIBERS'); ?></th><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JSTATUS'), 'a.state', $direction, $order); ?></th><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGRID_HEADING_ORDERING'), 'a.ordering', $direction, $order); ?></th><th class="w-3 text-center"><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGRID_HEADING_ID'), 'a.id', $direction, $order); ?></th></tr></thead><tbody>
	<?php foreach ($this->items as $i => $item) : ?><tr><td class="text-center"><?php echo HTMLHelper::_('grid.id', $i, (int) $item->id); ?></td><th><a href="<?php echo Route::_(AdministratorRoute::topic((int) $item->id)); ?>"><?php echo htmlspecialchars((string) $item->title, ENT_QUOTES, 'UTF-8'); ?></a><?php if ($item->description) : ?><div class="small text-muted"><?php echo htmlspecialchars((string) $item->description, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?></th><td><code><?php echo htmlspecialchars((string) $item->alias, ENT_QUOTES, 'UTF-8'); ?></code></td><td><?php echo (int) $item->subscriber_count; ?></td><td><?php echo (int) $item->state === 1 ? '<span class="badge bg-success">' . Text::_('JPUBLISHED') . '</span>' : ((int) $item->state === -2 ? '<span class="badge bg-secondary">' . Text::_('JTRASHED') . '</span>' : '<span class="badge bg-warning text-dark">' . Text::_('JUNPUBLISHED') . '</span>'); ?></td><td><?php echo (int) $item->ordering; ?></td><td class="text-center"><?php echo (int) $item->id; ?></td></tr><?php endforeach; ?>
	<?php if ($this->items === []) : ?><tr><td colspan="7" class="text-center text-muted py-4"><?php echo Text::_('COM_PUNGAMAIL_NO_TOPICS'); ?></td></tr><?php endif; ?>
	</tbody></table></div><?php echo $this->pagination->getListFooter(); ?><input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="filter_order" value="<?php echo htmlspecialchars($order, ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo htmlspecialchars($direction, ENT_QUOTES, 'UTF-8'); ?>"><?php echo HTMLHelper::_('form.token'); ?>
</form>
