<?php
/**
 * @package     Punga.Mail
 * @subpackage  Administrator.Controller
 * @copyright   Copyright (c) 2026 Punga
 * @license     MIT
 */

namespace Punga\Component\PungaMail\Administrator\Controller;

use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Controller\BaseController;
use Joomla\CMS\Response\JsonResponse;
use Joomla\CMS\Session\Session;
use Joomla\CMS\Uri\Uri;
use Punga\Component\PungaMail\Administrator\Service\ErrorMessage;
use Punga\Component\PungaMail\Administrator\Service\MarkdownRenderer;

/** AJAX endpoint for previews generated by Punga Mail's own Markdown renderer. */
final class MarkdownController extends BaseController
{
	/** @return void */
	public function preview(): void
	{
		$app = Factory::getApplication();

		try
		{
			if (!$app->getIdentity()->authorise('core.manage', 'com_pungamail'))
			{
				throw new \RuntimeException('Not authorised.');
			}

			if (!Session::checkToken('post'))
			{
				throw new \RuntimeException('Invalid security token.');
			}

			$markdown = (string) $app->getInput()->post->get('markdown', '', 'raw');
			$html = (new MarkdownRenderer())->toHtml($markdown, Uri::root());
			echo new JsonResponse(['html' => $html]);
		}
		catch (\Throwable $e)
		{
			echo new JsonResponse(null, ErrorMessage::sanitize($e), true);
		}

		$app->close();
	}
}
