<?php
/** @var \Punga\Component\PungaMail\Administrator\View\Digests\HtmlView $this */
defined('_JEXEC') or die;
use Joomla\CMS\Factory; use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Language\Text; use Joomla\CMS\Layout\LayoutHelper; use Joomla\CMS\Router\Route; use Punga\Component\PungaMail\Administrator\Service\AdministratorRoute;
$order=(string)$this->state->get('list.ordering');$direction=(string)$this->state->get('list.direction');$siteTimezone=(string)Factory::getApplication()->get('offset','UTC');
?>
<form action="<?php echo Route::_(AdministratorRoute::digests()); ?>" method="post" name="adminForm" id="adminForm"><?php echo LayoutHelper::render('joomla.searchtools.default',['view'=>$this]); ?><div class="table-responsive"><table class="table itemList"><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th><?php echo HTMLHelper::_('searchtools.sort',Text::_('JGLOBAL_TITLE'),'a.title',$direction,$order); ?></th><th><?php echo Text::_('COM_PUNGAMAIL_TEMPLATE'); ?></th><th><?php echo Text::_('COM_PUNGAMAIL_DIGEST_MODE'); ?></th><th><?php echo HTMLHelper::_('searchtools.sort',Text::_('COM_PUNGAMAIL_NEXT_RUN'),'a.next_run_at',$direction,$order); ?></th><th><?php echo Text::_('JSTATUS'); ?></th><th class="w-3 text-center"><?php echo HTMLHelper::_('searchtools.sort',Text::_('JGRID_HEADING_ID'),'a.id',$direction,$order); ?></th></tr></thead><tbody>
<?php foreach($this->items as $i=>$item):?><tr><td class="text-center"><?php echo HTMLHelper::_('grid.id',$i,(int)$item->id);?></td><th><a href="<?php echo Route::_(AdministratorRoute::digest((int)$item->id));?>"><?php echo htmlspecialchars((string)$item->title,ENT_QUOTES,'UTF-8');?></a></th><td><?php echo htmlspecialchars((string)($item->template_title??''),ENT_QUOTES,'UTF-8');?></td><td><span class="badge <?php echo (string)$item->generation_mode==='auto'?'bg-warning text-dark':'bg-info';?>"><?php echo Text::_((string)$item->generation_mode==='auto'?'COM_PUNGAMAIL_DIGEST_AUTO':'COM_PUNGAMAIL_DIGEST_DRAFT');?></span></td><td><?php echo HTMLHelper::_('date',$item->next_run_at,Text::_('DATE_FORMAT_LC5'),$siteTimezone);?></td><td><?php echo (int)$item->state===1?Text::_('JENABLED'):((int)$item->state===-2?Text::_('JTRASHED'):Text::_('JDISABLED'));?></td><td class="text-center"><?php echo (int)$item->id;?></td></tr><?php endforeach;?>
<?php if($this->items===[]):?><tr><td colspan="7" class="text-center text-muted py-4"><?php echo Text::_('COM_PUNGAMAIL_NO_DIGESTS');?></td></tr><?php endif;?></tbody></table></div><?php echo $this->pagination->getListFooter();?><input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="filter_order" value="<?php echo htmlspecialchars($order,ENT_QUOTES,'UTF-8');?>"><input type="hidden" name="filter_order_Dir" value="<?php echo htmlspecialchars($direction,ENT_QUOTES,'UTF-8');?>"><?php echo HTMLHelper::_('form.token');?></form>
