<?php
/** @var \Punga\Component\PungaMail\Administrator\View\Templates\HtmlView $this */
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Language\Text; use Joomla\CMS\Layout\LayoutHelper; use Joomla\CMS\Router\Route;
$listOrder = (string) $this->state->get('list.ordering'); $listDirn = (string) $this->state->get('list.direction');
?>
<?php echo \Joomla\CMS\Layout\LayoutHelper::render('pungamail.section_navigation', ['section' => 'design', 'active' => 'templates'], JPATH_ADMINISTRATOR . '/components/com_pungamail/layouts'); ?>
<form action="<?php echo Route::_(\Punga\Component\PungaMail\Administrator\Service\AdministratorRoute::templates()); ?>" method="post" name="adminForm" id="adminForm">
<?php echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]); ?>
<div class="table-responsive"><table class="table itemList"><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGLOBAL_TITLE'), 'a.title', $listDirn, $listOrder); ?></th><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('COM_PUNGAMAIL_SUBJECT'), 'a.subject', $listDirn, $listOrder); ?></th><th><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGLOBAL_FIELD_MODIFIED_LABEL'), 'a.modified', $listDirn, $listOrder); ?></th><th class="w-3 text-center"><?php echo HTMLHelper::_('searchtools.sort', Text::_('JGRID_HEADING_ID'), 'a.id', $listDirn, $listOrder); ?></th></tr></thead><tbody>
<?php foreach ($this->items as $i => $item) : ?><tr class=""><td class="text-center"><?php echo HTMLHelper::_('grid.id', $i, (int) $item->id); ?></td><th><a href="<?php echo Route::_(\Punga\Component\PungaMail\Administrator\Service\AdministratorRoute::template((int) $item->id)); ?>"><?php echo htmlspecialchars((string) $item->title, ENT_QUOTES, 'UTF-8'); ?></a></th><td><?php echo htmlspecialchars((string) $item->subject, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo HTMLHelper::_('date', $item->modified, Text::_('DATE_FORMAT_LC5'), 'UTC'); ?></td><td class="text-center"><?php echo (int) $item->id; ?></td></tr><?php endforeach; ?>
<?php if ($this->items === []) : ?><tr><td colspan="5" class="text-center text-muted py-4"><?php echo Text::_('COM_PUNGAMAIL_NO_TEMPLATES'); ?></td></tr><?php endif; ?>
</tbody></table></div><?php echo $this->pagination->getListFooter(); ?><input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="filter_order" value="<?php echo htmlspecialchars($listOrder, ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo htmlspecialchars($listDirn, ENT_QUOTES, 'UTF-8'); ?>"><?php echo HTMLHelper::_('form.token'); ?></form>
